version: '3.9'

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - ./.envs/.local/.postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
