# Generated by Django 3.2.9 on 2021-11-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20211114_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Администратор'), ('EDITOR', 'Редактор'), ('MEMBER', 'Участник')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.user'),
            preserve_default=False,
        ),
    ]
