# Generated by Django 3.2.9 on 2021-11-20 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20211114_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
