# Generated by Django 3.2.9 on 2021-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_rename_url_file_file'),
        ('tasks', '0002_alter_task_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
