# Generated by Django 3.2.9 on 2021-11-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='url',
        ),
    ]
