# Generated by Django 3.2.9 on 2021-11-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_file_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='file',
        ),
    ]
